name: Chris Brake Show
favicon: null
layout_spectrum: 0.29283262323588133
typography_spectrum: 0.8242960583884269
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.12020626245066524
  lightness: 0.3152597376611084
  saturation: 0.9289541253820062
  rhythmicContrast: 0.871661075623706
purpose: []
