name: Chris Brake Show
favicon: null
layout_spectrum: 0.84124
typography_spectrum: 0.8242960583884269
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#ff0000'
    - '#7f7f7f'
    - '#3f3f3f'
  brandStrength: 0.12020626245066524
  lightness: 0.3152597376611084
  saturation: 0.9289541253820062
  rhythmicContrast: 0.871661075623706
purpose: []
